#!/usr/bin/env sh

VERSION=`git describe --tags --always`
LDFLAGS="-X main.LD_VERSION $VERSION"
case `basename $0` in
build)
    go build -ldflags "$LDFLAGS"
    ;;
install)
    go install -ldflags "$LDFLAGS"
    ;;
run)
    if go build -ldflags "$LDFLAGS" ; then
        ./ury-listd-go
    fi
esac
